### ISSUE TITLE
Get access to the libretime docker hub organization

### ISSUE THREAD

**Issue by jooola** [ned-kelly/docker-multicontainer-libretime#35]
Hi @ned-kelly

We are trying to get access to the libretime docker hub organization, and I heard you are the person owning it. Is that correct ? Could you give use access to it ?

See https://github.com/libretime/organization/issues/22

**Comment by hairmare** [comment]
Hey @jooola I sent you an invite since i seem to own the thing (til...).

**Comment by jooola** [comment]
:laughing: this is a good one!

Sorry @ned-kelly for spamming you about this, no one gave me any answer, and you were the only lead we had.

@hairmare Thanks for the invite, we are slowly getting this organization back together!

**Comment by jooola** [comment]
@hairmare Do you by any chance also own the https://github.com/LibreTimeDocBot account ?

**Comment by ned-kelly** [comment]
Hi Gents,

Apologies - been away on holidays the past two weeks ... This all sorted now?

Cheers,
