### ISSUE TITLE
Pin Silan version in Docker Build

### ISSUE THREAD

**Issue by ned-kelly** [ned-kelly/docker-multicontainer-libretime#4]
See: https://github.com/LibreTime/libretime/issues/197 for details - Silian needs to be pinned to exact known working version for now - not latest build from Apt Repos.

References: https://github.com/ned-kelly/docker-multicontainer-libretime/issues/1

**Comment by frecuencialibre** [comment]
wget -qO- http://download.opensuse.org/repositories/home:/hairmare:/silan/Debian_7.0/Release.key   | apt-key add -
    echo 'deb http://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_16.04 ./'   > /etc/apt/sources.list.d/hairmare_silan.list
    apt-get update
    apt-get install silan

**Comment by frecuencialibre** [comment]
actually i think Liquidsoap 1.3.3 is in Debian sid already. @paddatrapper would know

**Comment by paddatrapper** [comment]
Yup, it is. And in Debian testing. I'm working on getting 1.3.4 uploaded before the freeze in Jan for the next stable release

**Comment by frecuencialibre** [comment]
Add a script to reprocess silan on all files: https://github.com/LibreTime/libretime/pull/324

**Comment by ned-kelly** [comment]
Closed - https://github.com/ned-kelly/docker-multicontainer-libretime/pull/18 is now in the Docker Hub image.
